#!/bin/bash
echo
echo
echo
echo "                 ##########################################"
echo "                 #                                        #"
echo "                 #                                        #"
echo "                 #              Szymon Mirr               #"
echo "                 #                                        #"
echo "                 #                                        #"
echo "                 #          Porzadkowanie zbioru          #"
echo "                 #                                        #"
echo "                 #                                        #"
echo "                 #     $(date)      #"
echo "                 #                                        #"
echo "                 #                                        #"  
echo "                 ##########################################" 
echo
echo
echo
echo "Podaj ilosc liczb"
read n
let i=0
while [ $i -lt $n ]
do
echo "Podaj liczbe numer $i:"
read t[$i]
i=$i+1
done

echo ${t[*]}


f=1
a=0
b=0
while [ $f -ne 0 ]
do
	f=0
	i=1
	j=1
	while [ $i -ne $n ]
	do
		j=$i+1
		a=${t[$i]}
		b=${t[$j]}
echo $i
echo $j
echo $a
echo $b
		if [ $b -lt $a ]
		then
			t[$i]=t[$j]
			t[$j]=$a
			f=1
			i=$i+1
		fi
	done
done
echo "Posortowana tablica: " ${t[*]}


