im=imread('obraz.jpg');
[im,map]=imread('obraz.jpg');
figure;
figure(1);
subplot(2,2,1);
imshow(im);
subplot(2,2,2);
imgray=rgb2gray(im);
imshow(imgray);
subplot(2,2,3);
imgray=imgray+80;
imshow(imgray);
subplot(2,2,4);
imbw=im2bw(im);
imshow(imbw);
figure(2);
subplot(2,2,1);
imshow(im);
subplot(2,2,2);
a = zeros(size(img, 1), size(img, 2));
imred=im(:,:,1);
imred2=cat(3,imred,a,a);
imshow(imred2);
subplot(2,2,3);
imblue=im(:,:,2);
imblue2 = cat(3, a, imblue, a);
imshow(imblue2);
subplot(2,2,4);
imyellow=im(:,:,3);
imyellow2 = cat(3, a, a, imyellow);
imshow(imyellow2);
figure(3);
subplot(1,2,1);
imshow(im);
subplot(1,2,2);
imshow(imrotate(im, 180));
